version: "3"
services:
  db:
    image: mysql:8.0.26
    platform: linux/amd64
    restart: always
    command:
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    container_name: mysql
    ports:
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=qwe123
      - TZ=Asia/Seoul
    volumes:
      - /Users/youdong-u/goormthon
